[versions]
agp = "8.2.2"
android-sdk-compile = "34"
android-sdk-min = "24"
android-sdk-target = "34"
jdk = "21"

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
mymusictool-android-application = { id = "org.fruzitent.mymusictool.android.application", version = "unknown" }
mymusictool-android-library = { id = "org.fruzitent.mymusictool.android.library", version = "unknown" }
