# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# @help: https://docs.docker.com/compose/compose-file

name: my_music_tool

services:
  kt:
    build:
      additional_contexts:
        rs: "../../rs/"
      context: ../
      dockerfile: ./docker/Dockerfile
      platforms:
        - "linux/amd64"
        # TODO: missing packages
        # - "linux/arm64"
      target: deps
    image: ghcr.io/fruzitent/my_music_tool-kt:latest
    pull_policy: if_not_present
    restart: always
    volumes:
      - type: volume
        source: kt_data
        target: /workspaces/
        volume:
          nocopy: true
      - type: bind
        source: ./jks/
        target: /workspaces/my_music_tool-kt/jks/
        read_only: true

volumes:
  kt_data:
